---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: awsdevops-fluxcd
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: awsdevops-fluxcd
