---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: awsdevops-fluxcd
  namespace: default
spec:
  interval: 7m0s # detect drift and undo kubectl edits every hour
  wait: true # wait for all applied resources to become ready
  timeout: 3m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # recreate resources on immutable fields changes
  targetNamespace: default # set the namespace for all resources
  sourceRef:
    kind: GitRepository
    name: awsdevops-fluxcd
    namespace: default
  path: "./deploy"
