---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: awsdevops-fluxcd
  namespace: flux-system
spec:
  interval: 2m
  path: ./deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: awsdevops-fluxcd
