apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
images:
- name: 663380234130.dkr.ecr.us-east-1.amazonaws.com/nginx
  newTag: b3c52f576aaeb5e23ce1c1578b0c129904603637
