# build.yml
on:
  pull_request:
    paths:
    - "**/*.yml"
    - "**/*.html"
    - "**/*.yaml"
    - "*.yaml"
  push:
    paths:
    - "**/*.yml"
    - "**/*.html"
    - "**/*.yaml"
    - "*.yaml"
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
  deploy:
    env:
      CONTAINER_IMAGE: nginx:${{ github.sha }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCOUNT_ID: 663380234130
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::663380234130:role/githubrole
        role-session-name: MySessionName
  

    

    - name: Checkout
      uses: actions/checkout@master

    # Add steps here like linting, testing, minification, etc.
      
    - name: Setup ECR
      run: |
        # Login to AWS ECR
        $( aws ecr get-login-password --region us-eat-1 > ./TOKEN )
        $( aws ecr --region us-east-1 | docker login --username AWS --password $TOKEN 663380234130.dkr.ecr.us-east-1.amazonaws.com )
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE .
 
    # Set image tag in kustomization

    - name: Set image tag
      run: |
          cd deploy
          kustomize edit set image $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
          cat kustomization.yaml
    - name: Commit kustomization
      run: |
          git config --local user.email "samim1000@gmail.com"
          git config --local user.name "samimcloud2020"
          git commit -a -m "$CONTAINER_IMAGE"
    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true       
    
    # Add additional steps here like scanning of image

    # Only push to registry on master
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        # Push image to AWS ECR
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
